import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { brierScore, expectedCalibrationError, reliabilityTable } from "../src/metrics.js";
import type { JudgePrediction } from "../src/metrics.js";

/**
 * Cross-repo calibration contract (#2): @engine/eval's ECE/Brier math is the
 * org's canonical calibration IP; sigil MIRRORS it — one-directionally, with
 * no dependency in either direction — and this test pins the mirror to the
 * committed golden generated by `pnpm --filter @engine/eval
 * gen:calibration-contract` in apatureai/judgment-engine (copied here). The
 * vectors include exact bin-edge confidences, the FP-sensitive inputs where a
 * binning-convention drift shows up first. If this test and the engine's sync
 * test ever disagree, one side changed the math unilaterally — the exact
 * failure mode the contract exists to catch.
 */

interface ContractVector {
  name: string;
  seed: number;
  count: number;
  bins: number;
  ece: number;
  brier: number;
  reliability: Array<{
    lower: number;
    upper: number;
    count: number;
    predictedMean: number;
    empiricalRate: number;
  }>;
}

const golden = JSON.parse(
  readFileSync(fileURLToPath(new URL("../fixtures/calibration-contract.golden.json", import.meta.url)), "utf8"),
) as { vectors: ContractVector[] };

/** Byte-for-byte mirror of @engine/eval's `contractPairs` generator. */
function contractPairs(seed: number, count: number): JudgePrediction[] {
  let s = seed >>> 0;
  const next = (): number => {
    s = (Math.imul(s, 1_664_525) + 1_013_904_223) >>> 0;
    return s;
  };
  const pairs: JudgePrediction[] = [];
  for (let i = 0; i < count; i++) {
    const confidence = (next() % 41) / 40;
    const correct = next() % 1000 < confidence * 1000;
    pairs.push({ confidence, correct });
  }
  return pairs;
}

describe("calibration contract with @engine/eval (#2)", () => {
  it("ships the expected vector set with bin-edge coverage", () => {
    expect(golden.vectors.length).toBeGreaterThanOrEqual(3);
    const confidences = golden.vectors.flatMap((v) => contractPairs(v.seed, v.count)).map((p) => p.confidence);
    for (const edge of [0.1, 0.3, 0.7, 1]) expect(confidences).toContain(edge);
  });

  it.each(golden.vectors.map((v) => [v.name, v] as const))(
    "sigil's ECE/Brier/reliability equal the engine's exactly for %s",
    (_name, v) => {
      const pairs = contractPairs(v.seed, v.count);
      expect(expectedCalibrationError(pairs, v.bins)).toBe(v.ece);
      expect(brierScore(pairs)).toBe(v.brier);
      const table = reliabilityTable(pairs, v.bins);
      expect(table.length).toBe(v.reliability.length);
      for (let i = 0; i < table.length; i++) {
        const ours = table[i]!;
        const theirs = v.reliability[i]!;
        expect(ours.count).toBe(theirs.count);
        expect(ours.predicted).toBe(theirs.predictedMean);
        expect(ours.empirical).toBe(theirs.empiricalRate);
      }
    },
  );
});
